### ISSUE TITLE
TKS DB Schema에 AWS 정보 추가

### ISSUE THREAD

**Issue by bluejayA** [sktelecom/tks-info#18]
**내용**

cspinfo에 type을 추가하여 aws, azure 등 CSP를 구분한다.
clusters에 region을 추가한다.
위의 변경사항에 따라 gRPC에 parameter를 변경한다.

**산출물**

tks-proto 변경
tks-cluster-lcm, tks-info 변경

**Comment by ktkfree** [comment]
오래된 이슈로 금번 스프린트의 다음 티켓과 함께 다시 PR 올리겠습니다.
 . [Dev] tks-info 추가개발: keycloak 관련 정보 저장 #10
 . https://app.zenhub.com/workspaces/tks-development-60c96f813019b5000e5b69c3/issues/sktelecom/tks-issues/10

본 PR 은 종료합니다.
